api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "Profile account summary"
handle = "profile-account-summary"
uid = "591a09fb-d5c8-2f53-1aa0-e4b2b9cb190c9eda233f"

[[extensions.targeting]]
target = "customer-account.profile.block.render"
module = "./src/ProfileSummary.jsx"

[extensions.capabilities]
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "custom_css"
type = "multi_line_text_field"
name = "Custom CSS"
description = "Add custom CSS to style the elements on this page."

